# Generated by Django 3.2.12 on 2023-12-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplyoee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplyoee_name', models.CharField(max_length=50)),
                ('emplyoee_id', models.IntegerField(default=0)),
                ('emplyoee_address', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('total_production', models.IntegerField(default=0)),
                ('machine_in_use', models.IntegerField(default=0)),
            ],
        ),
    ]
