# Generated by Django 3.2.12 on 2023-12-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=60)),
                ('current_output', models.IntegerField(default=0)),
                ('last_maintainance', models.DateField()),
            ],
        ),
    ]
