# Generated by Django 3.2.12 on 2023-12-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0003_alter_machine_last_maintainance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='last_maintainance',
            field=models.DateField(null=True),
        ),
    ]
