# Generated by Django 3.2.12 on 2023-12-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0004_alter_machine_last_maintainance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=60)),
                ('date', models.DateField(null=True)),
                ('production_output', models.IntegerField(default=0)),
                ('issues', models.TextField()),
            ],
        ),
    ]
