# Generated by Django 3.2.12 on 2023-12-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0005_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.IntegerField(default=0)),
                ('upcoming_maintainance', models.DateField(null=True)),
                ('recent_maintainance', models.DateField(null=True)),
            ],
        ),
    ]
