# Generated by Django 3.2.12 on 2023-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0006_maintainance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('date_placed', models.DateField(null=True)),
                ('customer_name', models.CharField(max_length=60)),
                ('contact_number', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=60)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=60)),
                ('total_paid', models.IntegerField(default=0)),
                ('delivery_status', models.CharField(max_length=60)),
                ('expected_del', models.DateField(null=True)),
            ],
        ),
    ]
