# Generated by Django 3.2.12 on 2023-12-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_identity',
        ),
        migrations.AlterField(
            model_name='production',
            name='current_time',
            field=models.DateField(null=True),
        ),
    ]
