# Generated by Django 3.2.12 on 2023-12-20 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0008_auto_20231220_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_identity',
        ),
    ]
